### ISSUE TITLE
Improving corectl config repository handling

### ISSUE THREAD

**Issue by withnale** [coreeng/corectl#99]
The only time corectl is aware explicitly of the environments repository is during the `corectl config init` command. Once initialised the `corectl.yaml` configuration file is generated similar to below, without the repo url being registered.

```yaml
github:
  token: ghp_mytoken
  organization: coreeng
repositories:
  cplatform: /Users/rhodesp/.config/corectl/repositories/core-platform-environments
  templates: /Users/rhodesp/.config/corectl/repositories/core-platform-software-templates
  allow-dirty: false
p2p:
  fast-feedback:
    default-envs:
      - gcp-dev
  extended-test:
    default-envs:
      - gcp-dev
  prod:
    default-envs:
      - gcp-prod
```

This causes some problems, since these repos are maintained as the staging locations for PRs directed by interactions with corectl. In the event that there are problems with these commands, the working tree can be left in a dirty state. In these circumstances, an easy option is often to wipe these directories, but to reinitialise the repos it is necessary to rerun `corectl config init`.

Ideally we should record the repo location in the corectl.yaml file, allowing `corectl config update` logic to re-clone the repository if the repo is missing. It might be beneficial to establish `corectl config update --force` as an option to remove the repositories and re-clone them, allowing such the "manual cleanup" process to be eliminated.
